/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrera_autos;

/**
 *
 * @author DELL
 */
public class Pista_de_Carreras extends javax.swing.JFrame {

    
    /**
     * Creates new form Pista_de_Carreras
     */
    public Pista_de_Carreras() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BanderaD = new javax.swing.JLabel();
        Bandera_Iz = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Rayo_Macqueen = new javax.swing.JLabel();
        Pista1 = new javax.swing.JLabel();
        Ramon = new javax.swing.JLabel();
        Jackso_Storm = new javax.swing.JLabel();
        Pista2 = new javax.swing.JLabel();
        Francesco = new javax.swing.JLabel();
        Pista3 = new javax.swing.JLabel();
        Pista4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BanderaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banderas.png"))); // NOI18N
        getContentPane().add(BanderaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        Bandera_Iz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banderas.png"))); // NOI18N
        getContentPane().add(Bandera_Iz, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 810, 81));

        Rayo_Macqueen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rayo Macqueen.png"))); // NOI18N
        getContentPane().add(Rayo_Macqueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 100, 80));

        Pista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pista.png"))); // NOI18N
        Pista1.setOpaque(true);
        getContentPane().add(Pista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 820, 100));

        Ramon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ramon.png"))); // NOI18N
        getContentPane().add(Ramon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        Jackso_Storm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Jackson Storm.png"))); // NOI18N
        getContentPane().add(Jackso_Storm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 100, 60));

        Pista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pista.png"))); // NOI18N
        getContentPane().add(Pista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 820, 100));

        Francesco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Francesco Bernoulli.png"))); // NOI18N
        getContentPane().add(Francesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        Pista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pista.png"))); // NOI18N
        getContentPane().add(Pista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 820, 100));

        Pista4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pista.png"))); // NOI18N
        getContentPane().add(Pista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 820, 100));

        jButton1.setText("START");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 517, -1, -1));

        jButton2.setText("STOP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 517, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pista_de_Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pista_de_Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pista_de_Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pista_de_Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pista_de_Carreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BanderaD;
    private javax.swing.JLabel Bandera_Iz;
    private javax.swing.JLabel Francesco;
    private javax.swing.JLabel Jackso_Storm;
    private javax.swing.JLabel Pista1;
    private javax.swing.JLabel Pista2;
    private javax.swing.JLabel Pista3;
    private javax.swing.JLabel Pista4;
    private javax.swing.JLabel Ramon;
    private javax.swing.JLabel Rayo_Macqueen;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
